In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# 1D arrays
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# shape() gives no. of rows and columns
a.shape

(3, 4)

In [ ]:
# 2D arrays
b = np.array([(1,2,3),[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.shape

(2, 3)

In [ ]:
c = np.array([(1,2,3,4),(6,7,8,9)], dtype = float)
print(c)

[[1. 2. 3. 4.]
 [6. 7. 8. 9.]]


In [ ]:
# creating array with zeros as values
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy arrays with values as ones
y = np.ones((3,3), dtype = int)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# array with a particular value
z = np.full((5,4),10)
print(z)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [ ]:
# create a identity matrix

a = np.eye(3, dtype = int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# create a numpy array with random values

a = np.random.random((3,4))
print(a)

[[0.44009141 0.5525813  0.8718201  0.38069856]
 [0.42349481 0.97570634 0.31506839 0.59558932]
 [0.42426143 0.50428155 0.43875943 0.19963976]]


In [ ]:
# numpy with random values with integers

c = np.random.randint(10,100,(2,5))
print(c)

[[60 92 62 52 33]
 [94 90 55 28 69]]


In [ ]:
# array with evenly spaced values

# (start, stop, no. of values)
z = np.linspace(10,30,7, dtype=int)
print(z)

[10 13 16 20 23 26 30]


In [ ]:
# array of evenly spaced values ---> specifying step
# (start, stop, space or diff btw no.s)
x = np.arange(10,30,5)
print(x)


[10 15 20 25]


In [ ]:
# convert a list to array

list2 = [10,20,20,20,50]

array = np.asarray(list2)
print(array)
type(array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
z = np.random.randint(10,90,(5,5))
print(z)


[[71 27 12 13 40]
 [34 29 45 46 69]
 [63 54 62 85 72]
 [56 18 27 59 84]
 [40 87 31 16 89]]


In [ ]:
# find dimension
z.shape

(5, 5)

In [ ]:
# no. of dimension
z.ndim

2

In [ ]:
# no. of elements
z.size

25

In [ ]:
# checking the datatype or values in a array

print(z.dtype)

int64


MATHEMATICAL OPERATIONS IN NUMPY ARRAY

In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[4 8 9]
 [4 9 9]
 [7 1 6]]
[[10 17 12]
 [19 10 10]
 [16 15 17]]


In [ ]:
# add, subtract , multiply and divide elemnets in array
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[14 25 21]
 [23 19 19]
 [23 16 23]]
[[ -6  -9  -3]
 [-15  -1  -1]
 [ -9 -14 -11]]
[[ 40 136 108]
 [ 76  90  90]
 [112  15 102]]
[[0.4        0.47058824 0.75      ]
 [0.21052632 0.9        0.9       ]
 [0.4375     0.06666667 0.35294118]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 25 21]
 [23 19 19]
 [23 16 23]]
[[ -6  -9  -3]
 [-15  -1  -1]
 [ -9 -14 -11]]
[[ 40 136 108]
 [ 76  90  90]
 [112  15 102]]
[[0.4        0.47058824 0.75      ]
 [0.21052632 0.9        0.9       ]
 [0.4375     0.06666667 0.35294118]]


**ARRAY MANIPULATION**

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 1 9]
 [8 0 2]]
(2, 3)


In [ ]:
# transpose of array matrix

trans = np.transpose(array)
print(trans)
print(trans.shape)

print()

trans2 = array.T
print(trans2)
print(trans2.shape)

[[1 8]
 [1 0]
 [9 2]]
(3, 2)

[[1 8]
 [1 0]
 [9 2]]
(3, 2)


In [ ]:
# reshaping a array

a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

print()

b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 4 2]
 [2 1 1]]
(2, 3)

[[3 4]
 [2 2]
 [1 1]]
(3, 2)
